version: "3"

services:
    server:
        build:
            context: .
            dockerfile: ./build/server/Dockerfile
        image: "hwwuex_check_server"
        network_mode: "host"
        ports:
        - "8888:8888"
        restart: always
        volumes:
        - /hcs:/hcs
        environment:
        - PYTHONPATH=:/root
        command: python3 /root/application/server/server.py -i 0.0.0.0 -p 8888
        container_name: "hc_server"