# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-27 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ('-create_at',),
            },
        ),
        migrations.CreateModel(
            name='ExitStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('color', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url', models.TextField()),
                ('job_dir', models.TextField()),
                ('ismonitored', models.BooleanField()),
                ('fetchSizeOfOneTime', models.IntegerField(default=1)),
                ('fetchFrequency', models.IntegerField(default=3600)),
                ('trainingFrequency', models.IntegerField(default=3600)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('codes_number', models.IntegerField()),
                ('istrainingset', models.BooleanField()),
                ('duration', models.FloatField(default=0.0)),
                ('timestamp', models.IntegerField(default=0)),
                ('description', models.TextField(null=True)),
                ('error_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webpage.ErrorType')),
                ('exit_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webpage.ExitStatus')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webpage.Job')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ('-create_at',),
            },
        ),
        migrations.AddField(
            model_name='log',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webpage.Team'),
        ),
    ]
