# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-26 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.TextField()),
                ('description', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ('-create_at',),
            },
        ),
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('upload_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('error_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webpage.ErrorType')),
            ],
            options={
                'ordering': ('-upload_time',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ('-create_at',),
            },
        ),
        migrations.AddField(
            model_name='logfile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webpage.Team'),
        ),
    ]
