# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-27 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('line_width', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PlotColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('character', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlotLineStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('character', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlotMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('character', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_num', models.IntegerField()),
                ('score', models.FloatField()),
                ('training_time', models.DateTimeField(auto_now_add=True)),
                ('duration', models.FloatField(default=0.0)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webpage.Job')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LogAnalysis.MLModel')),
            ],
            options={
                'ordering': ('-job', '-model', '-training_time'),
            },
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='line_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LogAnalysis.PlotLineStyle'),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='marker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LogAnalysis.PlotMarker'),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='plot_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LogAnalysis.PlotColor'),
        ),
    ]
